version: '3'

services:
  db:
    container_name: my_mysql
    image: mysql:8-debian
    command: mysqld --default-authentication-plugin=mysql_native_password --sql_mode=""
    environment:
      MYSQL_ROOT_PASSWORD: Password
      MYSQL_DATABASE: MyDB
    ports:
      - "3306:3306"
    volumes:
#      - ./my_sql_data:/var/lib/mysql                   # Bind Mount (This should be avoided unless in dev environments, in favor of Named Volumes instead)
      - mysql_data:/var/lib/mysql                       # Named Volume
      - ./db_entrypoint:/docker-entrypoint-initdb.d     # .sql dump in local db_entrypoint directory will be imported in the DB if no existing data in mysql_data volume 
    restart:
      unless-stopped

volumes:
  mysql_data: