version: '3'

services:
  db:
    container_name: my_mysql
    image: mysql:8-debian
    command: --default-authentication-plugin=mysql_native_password --sql_mode=
    environment:
      MYSQL_ROOT_PASSWORD: Master-123
      MYSQL_DATABASE: Test
    ports:
      - "3306:3306"
    volumes:
      - ./my_sql_data:/var/lib/mysql
      - ./db_entrypoint:/docker-entrypoint-initdb.d
    restart:
      unless-stopped